### ISSUE TITLE
Link Building

### ISSUE THREAD

**Issue by ezimerman** [Illexpert/illexpert.com#12]
1. Put up a fake job board page on the domain. Post bogus job ads with links to the site.
2. Add a description to your Github page, with link included. (Github does not add nofollow attributes to anchor tags). Use good anchor text. This ties back in with the value of having a webpage for each podcast. You can tap into the specificity of that podcast by using the appropriate anchor text.
3. Create/contribute to more Github repositories, add links to descriptions.

**Comment by Illexpert** [comment]
There's an ethical line I'd like not to cross. I don't like fake spamming even if it can accomplish short-term traffic. It's low and sleazy, and if Google found out they'd be upset, it violates standard corporate business ethics. That's why the great companies follow ethical rules from the start, even when they were tiny start-ups. Checkout the book Collins' Built to Last 
http://www.amazon.com/Built-Last-Successful-Visionary-Essentials/dp/0060516402

**Comment by Illexpert** [comment]
2. there already is a link to illexpert.com on my github page.
3. Perhaps, but that is sort of touching the spam threshold. Though if some other repo's working on something directly related, I'll brand Illexpert on any contributions

**Comment by ezimerman** [comment]
Yes, ethics aside, Google's grown better at identifying spam, which is not what I'm suggesting.

Relevant links where, as stated earlier, the anchor text has some specificity associated with the landing page. And the link needs to be strategically placed.
