### ISSUE TITLE
Audio Tweaks

### ISSUE THREAD

**Issue by ezimerman** [Illexpert/illexpert.com#18]
You need to find a way to mute your keyboard typing and mouse clicking. It sounds parents-basement-ish.

There's a mild echo that varies in level

Reduce talk latency. Try different platform.

**Comment by Illexpert** [comment]
that was actually an experiment with a finite-slope noise-gate transform,
in the past I'd use an infinite slope gate (straight vertical line) so that
cuts out everything. I'm replacing the track, let me know if you like the
second one better. We can do a show on stuff like this. Do you get the
difference between a finite-slope gate transform?

**Comment by Illexpert** [comment]
Watch out for replacement 065 - Let me know if you perceive quality improvement.
